# 📘 Esercizi su matrici multidimensionali e prodotto cartesiano

## 1️⃣ Somma degli ultimi due assi di una matrice quadridimensionale

### 🎯 Obiettivo:
Creare un programma che calcoli la **somma degli ultimi due assi** di una matrice quadridimensionale.

## 2️⃣ Prodotto cartesiano di un numero arbitrario di vettori

### 🎯 Obiettivo:
Dato un numero arbitrario di vettori, generare il **prodotto cartesiano**, ovvero tutte le possibili combinazioni tra gli elementi di ciascun vettore.

### 1️⃣ Somma degli ultimi due assi di una matrice quadridimensionale

In [1]:
import numpy as np

# Definire un array a 4 dimensioni con valori casuali tra 1 e 10
array_4d = np.random.randint(1, 10, size=(2, 3, 4, 5))

# Verificare che l'array abbia 4 dimensioni e mostrarne i dettagli
print("Numero di dimensioni dell'array:", array_4d.ndim)
print("Forma dell'array:", array_4d.shape)
print("Contenuto dell'array:")
print(array_4d)

# Calcolare la somma degli elementi in base ai suoi ultimi 2 assi
somma_assi = np.sum(array_4d, axis=(-2, -1))

# Mostrare il risultato della somma
print("\nSomma degli elementi in base ai suoi 2 ultimi assi:")
print(somma_assi)

Numero di dimensioni dell'array: 4
Forma dell'array: (2, 3, 4, 5)
Contenuto dell'array:
[[[[9 7 3 5 4]
   [6 4 2 7 6]
   [1 7 2 6 4]
   [8 9 8 1 3]]

  [[2 5 5 4 4]
   [3 1 7 9 1]
   [8 2 9 3 5]
   [2 7 7 1 4]]

  [[4 1 6 8 9]
   [7 1 5 1 9]
   [2 5 9 6 6]
   [7 1 4 8 1]]]


 [[[5 1 9 4 6]
   [3 2 1 3 8]
   [1 8 9 4 1]
   [7 9 7 9 7]]

  [[6 9 4 9 4]
   [8 6 9 1 7]
   [3 6 2 6 7]
   [8 4 5 6 8]]

  [[7 6 8 2 9]
   [4 9 6 6 4]
   [6 5 9 9 9]
   [1 3 6 7 9]]]]

Somma degli elementi in base ai suoi 2 ultimi assi:
[[102  89 100]
 [104 118 125]]


### 2️⃣ Prodotto cartesiano di un numero arbitrario di vettori

In [5]:
import random
from itertools import product  # Importiamo product per calcolare il prodotto cartesiano

# Generare una lista di vettori casuali
def generare_vettori():
    """
    Crea un numero casuale di vettori, ciascuno con lunghezza casuale.
    
    Returns:
        list: Una lista di vettori, dove ogni vettore è una lista di numeri interi casuali.
    """
    num_vettori = random.randint(2, 5)  # Numero casuale di vettori tra 2 e 5
    vettori = []
    
    # Creiamo ogni vettore con lunghezza e valori casuali
    for _ in range(num_vettori):
        lunghezza = random.randint(2, 5)  # Lunghezza casuale tra 2 e 5
        # Generiamo un vettore con valori interi casuali tra 1 e 10
        vettore = [random.randint(1, 10) for _ in range(lunghezza)]
        vettori.append(vettore)
    
    return vettori

# Funzione per calcolare il prodotto cartesiano
def prodotto_cartesiano(vettori):
    """
    Calcola il prodotto cartesiano di una lista di vettori.
    
    Args:
        vettori (list): Lista di vettori di cui calcolare il prodotto cartesiano.
    
    Returns:
        Stampa i vettori di input e tutte le combinazioni del prodotto cartesiano.
    """
    # Utilizziamo product() da itertools per calcolare il prodotto cartesiano
    # L'operatore * "spacchetta" la lista di vettori come argomenti separati
    risultato = list(product(*vettori))
    
    # Stampiamo i vettori di input per riferimento
    print("Vettori generati:")
    for i, v in enumerate(vettori, start=1):
        print(f"Vettore {i}: {v}")
    
    # Stampiamo tutte le combinazioni del prodotto cartesiano
    print("\nProdotto cartesiano:")
    for combinazione in risultato:
        print(combinazione)
    
    # NB: il numero totale di combinazioni sarà il prodotto delle lunghezze dei vettori
    print(f"\nNumero totale di combinazioni: {len(risultato)}")

# Esecuzione principale: generare vettori casuali e calcolare il prodotto cartesiano
vettori_casuali = generare_vettori()
prodotto_cartesiano(vettori_casuali)

Vettori generati:
Vettore 1: [7, 1]
Vettore 2: [6, 5, 1]
Vettore 3: [5, 8]
Vettore 4: [5, 5, 2, 8]
Vettore 5: [9, 8, 2]

Prodotto cartesiano:
(7, 6, 5, 5, 9)
(7, 6, 5, 5, 8)
(7, 6, 5, 5, 2)
(7, 6, 5, 5, 9)
(7, 6, 5, 5, 8)
(7, 6, 5, 5, 2)
(7, 6, 5, 2, 9)
(7, 6, 5, 2, 8)
(7, 6, 5, 2, 2)
(7, 6, 5, 8, 9)
(7, 6, 5, 8, 8)
(7, 6, 5, 8, 2)
(7, 6, 8, 5, 9)
(7, 6, 8, 5, 8)
(7, 6, 8, 5, 2)
(7, 6, 8, 5, 9)
(7, 6, 8, 5, 8)
(7, 6, 8, 5, 2)
(7, 6, 8, 2, 9)
(7, 6, 8, 2, 8)
(7, 6, 8, 2, 2)
(7, 6, 8, 8, 9)
(7, 6, 8, 8, 8)
(7, 6, 8, 8, 2)
(7, 5, 5, 5, 9)
(7, 5, 5, 5, 8)
(7, 5, 5, 5, 2)
(7, 5, 5, 5, 9)
(7, 5, 5, 5, 8)
(7, 5, 5, 5, 2)
(7, 5, 5, 2, 9)
(7, 5, 5, 2, 8)
(7, 5, 5, 2, 2)
(7, 5, 5, 8, 9)
(7, 5, 5, 8, 8)
(7, 5, 5, 8, 2)
(7, 5, 8, 5, 9)
(7, 5, 8, 5, 8)
(7, 5, 8, 5, 2)
(7, 5, 8, 5, 9)
(7, 5, 8, 5, 8)
(7, 5, 8, 5, 2)
(7, 5, 8, 2, 9)
(7, 5, 8, 2, 8)
(7, 5, 8, 2, 2)
(7, 5, 8, 8, 9)
(7, 5, 8, 8, 8)
(7, 5, 8, 8, 2)
(7, 1, 5, 5, 9)
(7, 1, 5, 5, 8)
(7, 1, 5, 5, 2)
(7, 1, 5, 5, 9)
(7, 1, 5, 5, 8)
(7, 1, 5, 

In [3]:
# E X T R A :  il seguente è un esercizio aggiuntivo, da me ideato e risolto durante il corso
# che ho deciso di migliorare e aggiungere al progetto come extra.

# Normalizzazione lungo un asse specifico di una matrice tridimensionale

## 🎯 Obiettivo
Scrivere un programma in Python (utilizzando NumPy) che:
- Prenda in input una matrice tridimensionale
- Calcoli la somma lungo un asse specifico
- Normalizzi i dati dividendo ogni elemento per la somma del proprio asse
- Restituisca la matrice normalizzata

In [6]:
import numpy as np


def normalizza_matrice(A: np.ndarray, axis: int) -> np.ndarray:
    """
    Normalizza un array NumPy N-dimensionale lungo un asse specificato.

    Args:
    A : np.ndarray
        Array NumPy di dimensione arbitraria.
    axis : int
        Asse lungo il quale effettuare la normalizzazione.

    Returns:
    np.ndarray
        Array normalizzato lungo l'asse specificato.

    Raises
    ------
    TypeError
        Se A non è un array NumPy o axis non è un intero.
    ValueError
        Se l'asse specificato non è valido per le dimensioni dell'array.
    """


# Controlli sugli input

    if not isinstance(A, np.ndarray):
        raise TypeError("L'input A deve essere un array NumPy.")

    if not isinstance(axis, int):
        raise TypeError("L'asse deve essere un numero intero.")

    if axis < -A.ndim or axis >= A.ndim:
        raise ValueError(
            f"Asse non valido. L'array ha {A.ndim} dimensioni.")


# Calcolo della somma lungo l'asse

    somme = np.sum(A, axis=axis, keepdims=True)

    # Evita divisioni per zero
    somme = np.where(somme == 0, 1, somme)

    # Normalizzazione
    A_normalizzata = A / somme

    return A_normalizzata


    # UTILIZZO
if __name__ == "__main__":

    A = np.array([
        [[1, 2, 3],
         [4, 5, 6]],
        
        [[7, 8, 9],
         [10, 11, 12]]
    ])

    axis_scelto = 2

    risultato = normalizza_matrice(A, axis_scelto)

    print("Matrice originale:\n", A)
    print("\nMatrice normalizzata lungo l'asse", axis_scelto, ":\n")
    print(risultato)

Matrice originale:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Matrice normalizzata lungo l'asse 2 :

[[[0.16666667 0.33333333 0.5       ]
  [0.26666667 0.33333333 0.4       ]]

 [[0.29166667 0.33333333 0.375     ]
  [0.3030303  0.33333333 0.36363636]]]
